[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_evoting = "GbzpQsWceMHsMLzAshjft5yvqt2m2ULdCJzCErGpRWR9"

[programs.devnet]
solana_evoting = "GbzpQsWceMHsMLzAshjft5yvqt2m2ULdCJzCErGpRWR9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = ""


[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.js"

[toolchain]
anchor_version = "0.31.1"
